version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db_perfumora
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DOCKER_DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  server:
    build: ./server
    container_name: node_server_perfumora
    restart: always
    ports:
      - "${PORT}:5000"
    env_file:
      - ./.env
    environment:
      DB_HOST: ${DOCKER_DB_HOST}
      DB_PORT: ${DOCKER_DB_PORT}
      DB_USER: ${DOCKER_DB_USER}
      DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      DB_NAME: ${DOCKER_DB_NAME}
    volumes:
      - ./server:/usr/src/app
      - ./server/src/data:/usr/src/app/data
    depends_on:
      - db
    networks:
      - app-network

  client:
    build: ./client
    container_name: react_client_perfumora
    ports:
      - "${CLIENT_PORT}:80"
    env_file:
      - ./.env
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
